[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  '@solady/=lib/solady/src/',
  '@solady-v0.0.245/=lib/solady-v0.0.245/src/',
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@layerzerolabs/=lib/LayerZero-v2/"
]

[rpc_endpoints]
# Current Base Sepolia (backwards compatibility)
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

# Multi-chain OFT deployment networks
eth_sepolia = "${ETH_SEPOLIA_RPC}"
op_sepolia = "${OP_SEPOLIA_RPC}"
base_sepolia_new = "${BASE_SEPOLIA_RPC}"
arb_sepolia = "${ARB_SEPOLIA_RPC}"

[etherscan]
# Current Base Sepolia (backwards compatibility)
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

# Multi-chain verification endpoints
eth_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
op_sepolia = { key = "${OPSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }
base_sepolia_new = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
arb_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }