[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-optionss

remappings = [
  '@solady/=lib/solady/src/',
  '@solady-v0.0.245/=lib/solady-v0.0.245/src/',
]
